# MultiPlot options saved by style manager
set ::MultiPlot::Plot0::title "Estimated distance between periodic images (SER4 CA - ASP144 CA) "
set ::MultiPlot::Plot0::titlefont "Courier"
set ::MultiPlot::Plot0::titlefontsize "20"
set ::MultiPlot::Plot0::linewidth "1"
set ::MultiPlot::Plot0::linecolor "black"
set ::MultiPlot::Plot0::radius "2"
set ::MultiPlot::Plot0::fillcolor "{#ee4643}"
set ::MultiPlot::Plot0::marker "point"
set ::MultiPlot::Plot0::ylabelfont "Courier"
set ::MultiPlot::Plot0::ylabelfontsize "10"
set ::MultiPlot::Plot0::xlabelfont "Courier"
set ::MultiPlot::Plot0::xlabelfontsize "10"
set ::MultiPlot::Plot0::ylabeltext "Distance [A]"
set ::MultiPlot::Plot0::xlabeltext "Sampled frames"
set ::MultiPlot::Plot0::ymin "   36.4462"
set ::MultiPlot::Plot0::ymax "    56.922"
set ::MultiPlot::Plot0::xmin "         0"
set ::MultiPlot::Plot0::xmax "      2001"
set ::MultiPlot::Plot0::canh "700"
set ::MultiPlot::Plot0::canw "1000"
::MultiPlot::Plot0::plothandle replot
